package org.nonprofitbookkeeping.persistence;

import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class DatabaseMigrationRecoveryTest
{
    @Test
    public void recoversCompleteSchemaWhenFlywayHistoryIsEmpty() throws Exception
    {
        String jdbcUrl = jdbcUrl("complete-schema");
        DatabaseMigrationService.migrateJdbcUrl(jdbcUrl);

        try (Connection connection = DriverManager.getConnection(jdbcUrl, "sa", "");
                Statement statement = connection.createStatement())
        {
            statement.executeUpdate("""
                    INSERT INTO chart_of_accounts (name, version, status)
                    VALUES ('Recovery sentinel', '1', 'ACTIVE')
                    """);
            statement.executeUpdate("DELETE FROM flyway_schema_history");
        }

        DatabaseMigrationService.migrateJdbcUrl(jdbcUrl);

        try (Connection connection = DriverManager.getConnection(jdbcUrl, "sa", "");
                Statement statement = connection.createStatement())
        {
            assertEquals(1L, scalarLong(statement,
                    "SELECT COUNT(*) FROM chart_of_accounts WHERE name = 'Recovery sentinel'"));
            assertEquals(1L, scalarLong(statement,
                    "SELECT COUNT(*) FROM flyway_schema_history "
                            + "WHERE version = '48' AND type = 'BASELINE' AND success = TRUE"));
            assertEquals(1L, scalarLong(statement,
                    "SELECT COUNT(*) FROM information_schema.tables "
                            + "WHERE lower(table_name) LIKE 'flyway_schema_history_orphaned_%'"));
        }
    }

    @Test
    public void migratesFreshSchemaNormally() throws Exception
    {
        String jdbcUrl = jdbcUrl("fresh-schema");

        DatabaseMigrationService.migrateJdbcUrl(jdbcUrl);

        try (Connection connection = DriverManager.getConnection(jdbcUrl, "sa", "");
                Statement statement = connection.createStatement())
        {
            assertEquals(1L, scalarLong(statement,
                    "SELECT COUNT(*) FROM flyway_schema_history "
                            + "WHERE version = '48' AND success = TRUE"));
            assertEquals(1L, scalarLong(statement,
                    "SELECT COUNT(*) FROM information_schema.columns "
                            + "WHERE lower(table_name) = 'txn' AND lower(column_name) = 'status'"));
        }
    }

    @Test
    public void rejectsPartialUntrackedSchemaWithoutDeletingData() throws Exception
    {
        String jdbcUrl = jdbcUrl("partial-schema");
        try (Connection connection = DriverManager.getConnection(jdbcUrl, "sa", "");
                Statement statement = connection.createStatement())
        {
            statement.executeUpdate("""
                    CREATE TABLE chart_of_accounts
                    (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(200) NOT NULL,
                        version VARCHAR(50) NOT NULL,
                        status VARCHAR(20) NOT NULL
                    )
                    """);
            statement.executeUpdate("""
                    INSERT INTO chart_of_accounts (name, version, status)
                    VALUES ('Partial sentinel', '1', 'ACTIVE')
                    """);
        }

        IllegalStateException exception = assertThrows(
                IllegalStateException.class,
                () -> DatabaseMigrationService.migrateJdbcUrl(jdbcUrl));

        assertTrue(exception.getMessage().contains("partial or non-contiguous untracked schema"));
        try (Connection connection = DriverManager.getConnection(jdbcUrl, "sa", "");
                Statement statement = connection.createStatement())
        {
            assertEquals(1L, scalarLong(statement,
                    "SELECT COUNT(*) FROM chart_of_accounts WHERE name = 'Partial sentinel'"));
            assertEquals(0L, scalarLong(statement,
                    "SELECT COUNT(*) FROM information_schema.tables "
                            + "WHERE lower(table_name) = 'account'"));
        }
    }

    private static String jdbcUrl(String name)
    {
        return "jdbc:h2:mem:" + name + '-' + UUID.randomUUID()
                + ";MODE=PostgreSQL"
                + ";DATABASE_TO_LOWER=TRUE"
                + ";DEFAULT_NULL_ORDERING=HIGH"
                + ";DB_CLOSE_DELAY=-1"
                + ";INIT=CREATE SCHEMA IF NOT EXISTS PUBLIC\\;SET SCHEMA PUBLIC";
    }

    private static long scalarLong(Statement statement, String sql) throws Exception
    {
        try (ResultSet rows = statement.executeQuery(sql))
        {
            rows.next();
            return rows.getLong(1);
        }
    }
}
