CREATE TABLE IF NOT EXISTS budget_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(200) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    effective_from DATE,
    effective_to DATE,
    description CLOB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_budget_category_code UNIQUE (code)
);

CREATE INDEX IF NOT EXISTS ix_budget_category_active
    ON budget_category (is_active);

CREATE INDEX IF NOT EXISTS ix_budget_category_name
    ON budget_category (name);

CREATE TABLE IF NOT EXISTS budget_category_alias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_category_id BIGINT NOT NULL,
    alias VARCHAR(200) NOT NULL,
    source_system VARCHAR(80),
    CONSTRAINT uq_budget_category_alias UNIQUE (alias),
    CONSTRAINT fk_budget_category_alias_category
        FOREIGN KEY (budget_category_id)
        REFERENCES budget_category (id)
);

CREATE INDEX IF NOT EXISTS ix_budget_category_alias_category
    ON budget_category_alias (budget_category_id);

ALTER TABLE txn_split
    ADD COLUMN IF NOT EXISTS budget_category_id BIGINT;

ALTER TABLE txn_split
    ADD CONSTRAINT IF NOT EXISTS fk_txn_split_budget_category
        FOREIGN KEY (budget_category_id)
        REFERENCES budget_category (id);

CREATE INDEX IF NOT EXISTS ix_split_budget_category
    ON txn_split (budget_category_id);
