CREATE TABLE IF NOT EXISTS company (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    legal_name VARCHAR(250),
    branch_type VARCHAR(80),
    parent_organization VARCHAR(200),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    fiscal_year_start_month INT NOT NULL DEFAULT 1,
    fiscal_year_start_day INT NOT NULL DEFAULT 1,
    default_currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    active_chart_of_accounts_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_company_code UNIQUE (code),
    CONSTRAINT fk_company_active_chart FOREIGN KEY (active_chart_of_accounts_id) REFERENCES chart_of_accounts (id)
);

CREATE INDEX IF NOT EXISTS ix_company_active ON company (is_active);
CREATE INDEX IF NOT EXISTS ix_company_display_name ON company (display_name);

CREATE TABLE IF NOT EXISTS company_bank_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    name VARCHAR(160) NOT NULL,
    institution_name VARCHAR(200),
    account_type VARCHAR(80),
    last_four VARCHAR(8),
    opening_balance DECIMAL(19,4) DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    notes VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_company_bank_account_company FOREIGN KEY (company_id) REFERENCES company (id)
);

CREATE INDEX IF NOT EXISTS ix_company_bank_account_company ON company_bank_account (company_id);
CREATE INDEX IF NOT EXISTS ix_company_bank_account_active ON company_bank_account (is_active);

CREATE TABLE IF NOT EXISTS company_tax_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    ein VARCHAR(40),
    tax_jurisdiction VARCHAR(120),
    filing_name VARCHAR(250),
    filing_address VARCHAR(1000),
    notes VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_company_tax_profile_company UNIQUE (company_id),
    CONSTRAINT fk_company_tax_profile_company FOREIGN KEY (company_id) REFERENCES company (id)
);

CREATE INDEX IF NOT EXISTS ix_company_tax_profile_company ON company_tax_profile (company_id);

CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL,
    display_name VARCHAR(160) NOT NULL,
    email VARCHAR(254),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_app_user_username UNIQUE (username)
);

CREATE INDEX IF NOT EXISTS ix_app_user_active ON app_user (is_active);
CREATE INDEX IF NOT EXISTS ix_app_user_email ON app_user (email);

CREATE TABLE IF NOT EXISTS app_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(1000),
    CONSTRAINT uq_app_role_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS user_company_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_company_role UNIQUE (user_id, company_id, role_id),
    CONSTRAINT fk_user_company_role_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_user_company_role_company FOREIGN KEY (company_id) REFERENCES company (id),
    CONSTRAINT fk_user_company_role_role FOREIGN KEY (role_id) REFERENCES app_role (id)
);

CREATE INDEX IF NOT EXISTS ix_user_company_role_user ON user_company_role (user_id);
CREATE INDEX IF NOT EXISTS ix_user_company_role_company ON user_company_role (company_id);
CREATE INDEX IF NOT EXISTS ix_user_company_role_role ON user_company_role (role_id);

MERGE INTO app_role (code, name, description) KEY (code) VALUES
    ('ADMIN', 'Administrator', 'Full application administration.'),
    ('MANAGER', 'Manager', 'Company management, approval, and oversight workflows.'),
    ('ACCOUNTANT', 'Accountant', 'Bookkeeping data entry and reporting workflows.'),
    ('VIEWER', 'Viewer', 'Read-only reporting and review access.');

MERGE INTO company (code, display_name, legal_name, branch_type, parent_organization, is_active, fiscal_year_start_month, fiscal_year_start_day, default_currency)
KEY (code) VALUES
    ('DEFAULT', 'Default Company', 'Default Company', 'Branch', NULL, TRUE, 1, 1, 'USD');
