CREATE TABLE accounting_period (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fiscal_year INT NOT NULL,
  period_number INT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  closed_at TIMESTAMP NULL,
  closed_by VARCHAR(200) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_accounting_period_year_number UNIQUE (fiscal_year, period_number),
  CONSTRAINT ck_accounting_period_number CHECK (period_number > 0),
  CONSTRAINT ck_accounting_period_dates CHECK (end_date >= start_date),
  CONSTRAINT ck_accounting_period_status CHECK (status IN ('OPEN', 'CLOSED'))
);

CREATE INDEX ix_accounting_period_dates ON accounting_period(start_date, end_date);
CREATE INDEX ix_accounting_period_status ON accounting_period(status);

CREATE TABLE period_reopen_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  accounting_period_id BIGINT NOT NULL,
  reopened_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reopened_by VARCHAR(200) NOT NULL,
  reason VARCHAR(1000) NULL,
  reopen_scope VARCHAR(40) NOT NULL,
  prior_status VARCHAR(20) NOT NULL,
  CONSTRAINT fk_period_reopen_period FOREIGN KEY (accounting_period_id) REFERENCES accounting_period(id),
  CONSTRAINT ck_period_reopen_scope CHECK (reopen_scope IN ('SINGLE_TRANSACTION', 'CURRENT_SESSION', 'UNTIL_MANUALLY_CLOSED')),
  CONSTRAINT ck_period_reopen_prior_status CHECK (prior_status IN ('OPEN', 'CLOSED'))
);

CREATE INDEX ix_period_reopen_period ON period_reopen_event(accounting_period_id);
CREATE INDEX ix_period_reopen_time ON period_reopen_event(reopened_at);

CREATE TABLE audit_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actor VARCHAR(200) NOT NULL,
  action_type VARCHAR(80) NOT NULL,
  entity_type VARCHAR(120) NOT NULL,
  entity_id VARCHAR(120) NULL,
  summary VARCHAR(500) NOT NULL,
  before_value CLOB NULL,
  after_value CLOB NULL,
  reason VARCHAR(1000) NULL
);

CREATE INDEX ix_audit_event_time ON audit_event(occurred_at);
CREATE INDEX ix_audit_event_entity ON audit_event(entity_type, entity_id);
CREATE INDEX ix_audit_event_action ON audit_event(action_type);
