CREATE TABLE txn_reconciliation_protection (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  txn_id BIGINT NOT NULL,
  reconciliation_run_id UUID NOT NULL,
  protected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  protected_by VARCHAR(200) NULL,
  notes VARCHAR(1000) NULL,
  CONSTRAINT fk_txn_reconciliation_protection_txn FOREIGN KEY (txn_id) REFERENCES txn(id) ON DELETE CASCADE,
  CONSTRAINT uq_txn_reconciliation_protection UNIQUE (txn_id, reconciliation_run_id)
);

CREATE INDEX ix_txn_reconciliation_protection_txn ON txn_reconciliation_protection(txn_id);
CREATE INDEX ix_txn_reconciliation_protection_run ON txn_reconciliation_protection(reconciliation_run_id);
