-- V4: append-only journal tables + open-item snapshot and transition history

CREATE TABLE journal_transaction (
  id UUID PRIMARY KEY,
  group_code VARCHAR(64) NOT NULL,
  posted_on DATE NOT NULL,
  memo VARCHAR(500) NOT NULL,
  bank_timing VARCHAR(20) NOT NULL,
  budget_timing VARCHAR(20) NOT NULL,
  reversed_transaction_id UUID NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_journal_txn_group_posted ON journal_transaction(group_code, posted_on);
CREATE INDEX ix_journal_txn_reversed ON journal_transaction(reversed_transaction_id);

CREATE TABLE journal_posting_line (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id UUID NOT NULL,
  line_order INT NOT NULL,
  account_code VARCHAR(64) NOT NULL,
  fund_code VARCHAR(64) NOT NULL,
  entry_side VARCHAR(10) NOT NULL,
  amount DECIMAL(19,4) NOT NULL,
  CONSTRAINT fk_journal_line_txn FOREIGN KEY (transaction_id)
    REFERENCES journal_transaction(id) ON DELETE CASCADE,
  CONSTRAINT uq_journal_line_order UNIQUE (transaction_id, line_order)
);

CREATE INDEX ix_journal_line_txn ON journal_posting_line(transaction_id);
CREATE INDEX ix_journal_line_account_fund ON journal_posting_line(account_code, fund_code);

CREATE TABLE open_item_snapshot (
  id UUID PRIMARY KEY,
  group_code VARCHAR(64) NOT NULL,
  item_kind VARCHAR(40) NOT NULL,
  item_ref VARCHAR(120) NOT NULL,
  state VARCHAR(40) NOT NULL,
  original_amount DECIMAL(19,4) NOT NULL,
  open_amount DECIMAL(19,4) NOT NULL,
  last_transaction_id UUID NULL,
  last_updated_on DATE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_open_item_group_ref UNIQUE (group_code, item_kind, item_ref)
);

CREATE INDEX ix_open_item_group_kind_state ON open_item_snapshot(group_code, item_kind, state);

CREATE TABLE open_item_transition (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_id UUID NOT NULL,
  transition_on DATE NOT NULL,
  from_state VARCHAR(40) NOT NULL,
  to_state VARCHAR(40) NOT NULL,
  trigger_transaction_id UUID NULL,
  notes VARCHAR(500) NULL,
  CONSTRAINT fk_open_item_transition_snapshot FOREIGN KEY (snapshot_id)
    REFERENCES open_item_snapshot(id) ON DELETE CASCADE
);

CREATE INDEX ix_open_item_transition_snapshot ON open_item_transition(snapshot_id, transition_on);
