CREATE TABLE IF NOT EXISTS budget_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    fiscal_year INTEGER NOT NULL,
    version_code VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    activated_at TIMESTAMP WITH TIME ZONE,
    archived_at TIMESTAMP WITH TIME ZONE,
    notes CLOB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_budget_plan_fiscal_version UNIQUE (fiscal_year, version_code),
    CONSTRAINT ck_budget_plan_status CHECK (status IN ('DRAFT', 'ACTIVE', 'ARCHIVED')),
    CONSTRAINT ck_budget_plan_period CHECK (period_end >= period_start),
    CONSTRAINT ck_budget_plan_activation CHECK (
        (status = 'ACTIVE' AND activated_at IS NOT NULL AND archived_at IS NULL)
        OR (status = 'ARCHIVED' AND archived_at IS NOT NULL)
        OR (status = 'DRAFT' AND archived_at IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS ix_budget_plan_status ON budget_plan (status);
CREATE INDEX IF NOT EXISTS ix_budget_plan_fiscal_year ON budget_plan (fiscal_year);
CREATE INDEX IF NOT EXISTS ix_budget_plan_active_year ON budget_plan (fiscal_year, activated_at);

CREATE TABLE IF NOT EXISTS budget_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_plan_id BIGINT NOT NULL,
    budget_category_id BIGINT NOT NULL,
    fund_id BIGINT,
    period_month VARCHAR(7),
    fund_scope BIGINT GENERATED ALWAYS AS (COALESCE(fund_id, -1)),
    period_scope VARCHAR(7) GENERATED ALWAYS AS (COALESCE(period_month, 'ANNUAL')),
    amount NUMERIC(19,4) NOT NULL,
    notes CLOB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_budget_line_plan FOREIGN KEY (budget_plan_id) REFERENCES budget_plan (id),
    CONSTRAINT fk_budget_line_category FOREIGN KEY (budget_category_id) REFERENCES budget_category (id),
    CONSTRAINT fk_budget_line_fund FOREIGN KEY (fund_id) REFERENCES fund (id),
    CONSTRAINT uq_budget_line_scope UNIQUE (budget_plan_id, budget_category_id, fund_scope, period_scope),
    CONSTRAINT ck_budget_line_period_month CHECK (period_month IS NULL OR period_month LIKE '____-__')
);

CREATE INDEX IF NOT EXISTS ix_budget_line_plan ON budget_line (budget_plan_id);
CREATE INDEX IF NOT EXISTS ix_budget_line_category ON budget_line (budget_category_id);
CREATE INDEX IF NOT EXISTS ix_budget_line_fund ON budget_line (fund_id);
CREATE INDEX IF NOT EXISTS ix_budget_line_period ON budget_line (period_month);
