CREATE TABLE bank_import_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    bank_account_id BIGINT,
    source_name VARCHAR(260) NOT NULL,
    source_path VARCHAR(1000),
    source_hash VARCHAR(128),
    source_format VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'IMPORTED',
    imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    imported_by_user_id BIGINT,
    total_line_count INTEGER NOT NULL DEFAULT 0,
    accepted_line_count INTEGER NOT NULL DEFAULT 0,
    rejected_line_count INTEGER NOT NULL DEFAULT 0,
    issue_count INTEGER NOT NULL DEFAULT 0,
    notes VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bank_import_batch_company FOREIGN KEY (company_id) REFERENCES company(id),
    CONSTRAINT fk_bank_import_batch_bank_account FOREIGN KEY (bank_account_id) REFERENCES company_bank_account(id),
    CONSTRAINT fk_bank_import_batch_user FOREIGN KEY (imported_by_user_id) REFERENCES app_user(id),
    CONSTRAINT ck_bank_import_batch_format CHECK (source_format IN ('OFX', 'QFX', 'QIF', 'CSV', 'SCLX', 'OTHER')),
    CONSTRAINT ck_bank_import_batch_status CHECK (status IN ('IMPORTED', 'PARTIALLY_ACCEPTED', 'ACCEPTED', 'REJECTED', 'FAILED', 'CANCELLED')),
    CONSTRAINT ck_bank_import_batch_counts CHECK (total_line_count >= 0 AND accepted_line_count >= 0 AND rejected_line_count >= 0 AND issue_count >= 0)
);

CREATE INDEX ix_bank_import_batch_company ON bank_import_batch(company_id);
CREATE INDEX ix_bank_import_batch_bank_account ON bank_import_batch(bank_account_id);
CREATE INDEX ix_bank_import_batch_status ON bank_import_batch(status);
CREATE INDEX ix_bank_import_batch_source_hash ON bank_import_batch(company_id, source_hash);

CREATE TABLE bank_statement_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    bank_account_id BIGINT,
    source_row_number INTEGER NOT NULL,
    source_transaction_id VARCHAR(160),
    deterministic_fingerprint VARCHAR(128) NOT NULL,
    statement_account_identifier VARCHAR(160),
    transaction_date DATE NOT NULL,
    posted_date DATE,
    amount DECIMAL(19, 4) NOT NULL,
    transaction_type VARCHAR(40),
    name VARCHAR(260),
    memo VARCHAR(1000),
    check_number VARCHAR(80),
    reference VARCHAR(160),
    status VARCHAR(30) NOT NULL DEFAULT 'IMPORTED',
    disposition_note VARCHAR(1000),
    accepted_txn_id BIGINT,
    matched_txn_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bank_statement_line_batch FOREIGN KEY (batch_id) REFERENCES bank_import_batch(id),
    CONSTRAINT fk_bank_statement_line_company FOREIGN KEY (company_id) REFERENCES company(id),
    CONSTRAINT fk_bank_statement_line_bank_account FOREIGN KEY (bank_account_id) REFERENCES company_bank_account(id),
    CONSTRAINT fk_bank_statement_line_accepted_txn FOREIGN KEY (accepted_txn_id) REFERENCES txn(id),
    CONSTRAINT fk_bank_statement_line_matched_txn FOREIGN KEY (matched_txn_id) REFERENCES txn(id),
    CONSTRAINT uq_bank_statement_line_batch_row UNIQUE (batch_id, source_row_number),
    CONSTRAINT uq_bank_statement_line_batch_fingerprint UNIQUE (batch_id, deterministic_fingerprint),
    CONSTRAINT ck_bank_statement_line_status CHECK (status IN ('IMPORTED', 'ACCEPTED', 'REJECTED', 'MATCHED', 'DUPLICATE', 'ERROR')),
    CONSTRAINT ck_bank_statement_line_amount CHECK (amount <> 0),
    CONSTRAINT ck_bank_statement_line_disposition CHECK ((status = 'ACCEPTED' AND accepted_txn_id IS NOT NULL) OR (status = 'MATCHED' AND matched_txn_id IS NOT NULL) OR (status NOT IN ('ACCEPTED', 'MATCHED')))
);

CREATE INDEX ix_bank_statement_line_batch ON bank_statement_line(batch_id);
CREATE INDEX ix_bank_statement_line_company_date ON bank_statement_line(company_id, transaction_date);
CREATE INDEX ix_bank_statement_line_bank_account_date ON bank_statement_line(bank_account_id, transaction_date);
CREATE INDEX ix_bank_statement_line_source_id ON bank_statement_line(company_id, source_transaction_id);
CREATE INDEX ix_bank_statement_line_fingerprint ON bank_statement_line(company_id, deterministic_fingerprint);
CREATE INDEX ix_bank_statement_line_status ON bank_statement_line(status);

CREATE TABLE import_issue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    statement_line_id BIGINT,
    source_row_number INTEGER,
    severity VARCHAR(20) NOT NULL,
    code VARCHAR(80) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_import_issue_batch FOREIGN KEY (batch_id) REFERENCES bank_import_batch(id),
    CONSTRAINT fk_import_issue_statement_line FOREIGN KEY (statement_line_id) REFERENCES bank_statement_line(id),
    CONSTRAINT ck_import_issue_severity CHECK (severity IN ('INFO', 'WARNING', 'ERROR'))
);

CREATE INDEX ix_import_issue_batch ON import_issue(batch_id);
CREATE INDEX ix_import_issue_line ON import_issue(statement_line_id);
CREATE INDEX ix_import_issue_severity ON import_issue(severity);
