CREATE TABLE IF NOT EXISTS bank (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    routing_number VARCHAR(40),
    address VARCHAR(1000),
    website VARCHAR(500),
    contact_name VARCHAR(200),
    contact_phone VARCHAR(80),
    contact_email VARCHAR(254),
    notes VARCHAR(1000),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bank_company FOREIGN KEY (company_id) REFERENCES company(id),
    CONSTRAINT uq_bank_company_name UNIQUE (company_id, name)
);

CREATE INDEX IF NOT EXISTS ix_bank_company ON bank(company_id);
CREATE INDEX IF NOT EXISTS ix_bank_active ON bank(is_active);

ALTER TABLE company_bank_account ADD COLUMN IF NOT EXISTS bank_id BIGINT;
ALTER TABLE company_bank_account ADD COLUMN IF NOT EXISTS account_id BIGINT;
ALTER TABLE company_bank_account ADD COLUMN IF NOT EXISTS masked_account_number VARCHAR(80);
ALTER TABLE company_bank_account ADD COLUMN IF NOT EXISTS nickname VARCHAR(160);
ALTER TABLE company_bank_account ADD COLUMN IF NOT EXISTS opening_date DATE;
ALTER TABLE company_bank_account ADD COLUMN IF NOT EXISTS statement_import_format VARCHAR(20);
ALTER TABLE company_bank_account ADD COLUMN IF NOT EXISTS ofx_bank_id VARCHAR(80);
ALTER TABLE company_bank_account ADD COLUMN IF NOT EXISTS ofx_account_id VARCHAR(120);

ALTER TABLE company_bank_account ADD CONSTRAINT IF NOT EXISTS fk_company_bank_account_bank FOREIGN KEY (bank_id) REFERENCES bank(id);
ALTER TABLE company_bank_account ADD CONSTRAINT IF NOT EXISTS fk_company_bank_account_account FOREIGN KEY (account_id) REFERENCES account(id);
ALTER TABLE company_bank_account ADD CONSTRAINT IF NOT EXISTS uq_company_bank_account_account UNIQUE (company_id, account_id);
ALTER TABLE company_bank_account ADD CONSTRAINT IF NOT EXISTS ck_company_bank_account_import_format CHECK (statement_import_format IS NULL OR statement_import_format IN ('OFX', 'QFX', 'QIF', 'CSV'));

CREATE INDEX IF NOT EXISTS ix_company_bank_account_bank ON company_bank_account(bank_id);
CREATE INDEX IF NOT EXISTS ix_company_bank_account_account ON company_bank_account(account_id);
