CREATE TABLE IF NOT EXISTS fixed_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    asset_account_id BIGINT NOT NULL,
    accumulated_depreciation_account_id BIGINT NOT NULL,
    depreciation_expense_account_id BIGINT NOT NULL,
    fund_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    acquisition_date DATE NOT NULL,
    acquisition_cost DECIMAL(19,4) NOT NULL,
    salvage_value DECIMAL(19,4) NOT NULL DEFAULT 0,
    useful_life_months INTEGER NOT NULL,
    depreciation_method VARCHAR(40) NOT NULL,
    opening_accumulated_depreciation DECIMAL(19,4) NOT NULL DEFAULT 0,
    status VARCHAR(40) NOT NULL,
    notes CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fixed_asset_company FOREIGN KEY (company_id) REFERENCES company(id),
    CONSTRAINT fk_fixed_asset_asset_account FOREIGN KEY (asset_account_id) REFERENCES account(id),
    CONSTRAINT fk_fixed_asset_accum_dep_account FOREIGN KEY (accumulated_depreciation_account_id) REFERENCES account(id),
    CONSTRAINT fk_fixed_asset_dep_expense_account FOREIGN KEY (depreciation_expense_account_id) REFERENCES account(id),
    CONSTRAINT fk_fixed_asset_fund FOREIGN KEY (fund_id) REFERENCES fund(id),
    CONSTRAINT ck_fixed_asset_cost_nonnegative CHECK (acquisition_cost >= 0),
    CONSTRAINT ck_fixed_asset_salvage_nonnegative CHECK (salvage_value >= 0),
    CONSTRAINT ck_fixed_asset_opening_dep_nonnegative CHECK (opening_accumulated_depreciation >= 0),
    CONSTRAINT ck_fixed_asset_life_allowed CHECK (useful_life_months IN (36, 60, 84)),
    CONSTRAINT ck_fixed_asset_method CHECK (depreciation_method IN ('STRAIGHT_LINE')),
    CONSTRAINT ck_fixed_asset_status CHECK (status IN ('ACTIVE', 'DISPOSED', 'INACTIVE'))
);

CREATE INDEX IF NOT EXISTS ix_fixed_asset_company ON fixed_asset(company_id);
CREATE INDEX IF NOT EXISTS ix_fixed_asset_account ON fixed_asset(asset_account_id);
CREATE INDEX IF NOT EXISTS ix_fixed_asset_status ON fixed_asset(status);

CREATE TABLE IF NOT EXISTS fixed_asset_depreciation_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixed_asset_id BIGINT NOT NULL,
    run_date DATE NOT NULL,
    depreciation_amount DECIMAL(19,4) NOT NULL,
    transaction_id BIGINT NOT NULL,
    notes CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fixed_asset_dep_run_asset FOREIGN KEY (fixed_asset_id) REFERENCES fixed_asset(id),
    CONSTRAINT fk_fixed_asset_dep_run_txn FOREIGN KEY (transaction_id) REFERENCES txn(id),
    CONSTRAINT uq_fixed_asset_dep_run_period UNIQUE (fixed_asset_id, run_date),
    CONSTRAINT ck_fixed_asset_dep_run_amount CHECK (depreciation_amount > 0)
);

CREATE INDEX IF NOT EXISTS ix_fixed_asset_dep_run_asset ON fixed_asset_depreciation_run(fixed_asset_id);
CREATE INDEX IF NOT EXISTS ix_fixed_asset_dep_run_txn ON fixed_asset_depreciation_run(transaction_id);
