CREATE TABLE IF NOT EXISTS inventory_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    inventory_account_id BIGINT NOT NULL,
    fund_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    item_type VARCHAR(120) NOT NULL,
    quantity DECIMAL(19,4) NOT NULL,
    unit VARCHAR(40) NOT NULL,
    unit_value DECIMAL(19,4) NOT NULL DEFAULT 0,
    acquisition_date DATE NOT NULL,
    custodian VARCHAR(200),
    storage_location VARCHAR(200),
    item_condition VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL,
    notes CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventory_item_company FOREIGN KEY (company_id) REFERENCES company(id),
    CONSTRAINT fk_inventory_item_account FOREIGN KEY (inventory_account_id) REFERENCES account(id),
    CONSTRAINT fk_inventory_item_fund FOREIGN KEY (fund_id) REFERENCES fund(id),
    CONSTRAINT ck_inventory_item_quantity_nonnegative CHECK (quantity >= 0),
    CONSTRAINT ck_inventory_item_value_nonnegative CHECK (unit_value >= 0),
    CONSTRAINT ck_inventory_item_condition CHECK (item_condition IN ('UNKNOWN', 'GOOD', 'FAIR', 'POOR', 'DAMAGED')),
    CONSTRAINT ck_inventory_item_status CHECK (status IN ('ACTIVE', 'DISPOSED', 'INACTIVE'))
);

CREATE INDEX IF NOT EXISTS ix_inventory_item_company ON inventory_item(company_id);
CREATE INDEX IF NOT EXISTS ix_inventory_item_account ON inventory_item(inventory_account_id);
CREATE INDEX IF NOT EXISTS ix_inventory_item_status ON inventory_item(status);

CREATE TABLE IF NOT EXISTS inventory_movement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_item_id BIGINT NOT NULL,
    movement_date DATE NOT NULL,
    movement_type VARCHAR(40) NOT NULL,
    quantity_change DECIMAL(19,4) NOT NULL,
    resulting_quantity DECIMAL(19,4) NOT NULL,
    unit_value DECIMAL(19,4) NOT NULL DEFAULT 0,
    transaction_id BIGINT,
    notes CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventory_movement_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_item(id),
    CONSTRAINT fk_inventory_movement_txn FOREIGN KEY (transaction_id) REFERENCES txn(id),
    CONSTRAINT ck_inventory_movement_type CHECK (movement_type IN ('RECEIPT', 'ISSUE', 'ADJUSTMENT')),
    CONSTRAINT ck_inventory_movement_resulting_quantity CHECK (resulting_quantity >= 0),
    CONSTRAINT ck_inventory_movement_unit_value CHECK (unit_value >= 0)
);

CREATE INDEX IF NOT EXISTS ix_inventory_movement_item ON inventory_movement(inventory_item_id);
CREATE INDEX IF NOT EXISTS ix_inventory_movement_date ON inventory_movement(movement_date);
CREATE INDEX IF NOT EXISTS ix_inventory_movement_txn ON inventory_movement(transaction_id);
