CREATE TABLE IF NOT EXISTS bank_reconciliation_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    bank_account_id BIGINT NOT NULL,
    statement_start_date DATE NOT NULL,
    statement_end_date DATE NOT NULL,
    statement_ending_balance DECIMAL(19, 4),
    mismatch_policy VARCHAR(50) NOT NULL DEFAULT 'WARN_ONLY',
    status VARCHAR(30) NOT NULL DEFAULT 'IN_PROGRESS',
    notes VARCHAR(1000),
    beginning_balance DECIMAL(19, 4) NOT NULL DEFAULT 0,
    book_balance_all DECIMAL(19, 4) NOT NULL DEFAULT 0,
    book_balance_cleared DECIMAL(19, 4) NOT NULL DEFAULT 0,
    difference_amount DECIMAL(19, 4) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bank_reconciliation_session_company FOREIGN KEY (company_id) REFERENCES company(id),
    CONSTRAINT fk_bank_reconciliation_session_bank_account FOREIGN KEY (bank_account_id) REFERENCES company_bank_account(id),
    CONSTRAINT ck_bank_reconciliation_session_dates CHECK (statement_start_date <= statement_end_date),
    CONSTRAINT ck_bank_reconciliation_session_policy CHECK (mismatch_policy IN ('WARN_ONLY', 'OVERWRITE_LEDGER_CLEARED_STATE', 'NEVER_OVERWRITE_REQUIRE_MANUAL', 'DECIDE_PER_IMPORTED_LINE')),
    CONSTRAINT ck_bank_reconciliation_session_status CHECK (status IN ('IN_PROGRESS', 'UNRESOLVED', 'BALANCED', 'FINALIZED'))
);

CREATE INDEX IF NOT EXISTS ix_bank_reconciliation_session_company ON bank_reconciliation_session(company_id);
CREATE INDEX IF NOT EXISTS ix_bank_reconciliation_session_bank_account ON bank_reconciliation_session(bank_account_id);
CREATE INDEX IF NOT EXISTS ix_bank_reconciliation_session_statement_end ON bank_reconciliation_session(statement_end_date);
CREATE INDEX IF NOT EXISTS ix_bank_reconciliation_session_status ON bank_reconciliation_session(status);

CREATE TABLE IF NOT EXISTS bank_reconciliation_match (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    statement_line_id BIGINT,
    txn_split_id BIGINT,
    match_status VARCHAR(40) NOT NULL,
    resolution_note VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bank_reconciliation_match_session FOREIGN KEY (session_id) REFERENCES bank_reconciliation_session(id),
    CONSTRAINT fk_bank_reconciliation_match_statement FOREIGN KEY (statement_line_id) REFERENCES bank_statement_line(id),
    CONSTRAINT fk_bank_reconciliation_match_split FOREIGN KEY (txn_split_id) REFERENCES txn_split(id),
    CONSTRAINT ck_bank_reconciliation_match_status CHECK (match_status IN ('MATCHED', 'UNMATCHED', 'AMOUNT_MISMATCH', 'DATE_MISMATCH', 'DUPLICATE_POSSIBLE', 'CLEARED_STATE_MISMATCH', 'RESOLVED')),
    CONSTRAINT ck_bank_reconciliation_match_has_line CHECK (statement_line_id IS NOT NULL OR txn_split_id IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS ix_bank_reconciliation_match_session ON bank_reconciliation_match(session_id);
CREATE INDEX IF NOT EXISTS ix_bank_reconciliation_match_statement ON bank_reconciliation_match(statement_line_id);
CREATE INDEX IF NOT EXISTS ix_bank_reconciliation_match_split ON bank_reconciliation_match(txn_split_id);
