CREATE TABLE IF NOT EXISTS txn_supplemental_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    txn_id BIGINT NOT NULL,
    line_order INTEGER NOT NULL DEFAULT 0,
    kind VARCHAR(40) NOT NULL,
    entry_ref VARCHAR(200),
    counterparty VARCHAR(255),
    description VARCHAR(500) NOT NULL,
    reference VARCHAR(200),
    amount DECIMAL(19, 4) NOT NULL DEFAULT 0,
    due_date DATE,
    start_date DATE,
    end_date DATE,
    notes VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_txn_supplemental_line_txn FOREIGN KEY (txn_id) REFERENCES txn(id),
    CONSTRAINT ck_txn_supplemental_line_kind CHECK (kind IN ('RECEIVABLE', 'PAYABLE', 'PREPAID_EXPENSE', 'DEFERRED_REVENUE', 'OTHER_ASSET', 'OTHER_LIABILITY')),
    CONSTRAINT ck_txn_supplemental_line_amount CHECK (amount >= 0),
    CONSTRAINT ck_txn_supplemental_line_dates CHECK ((start_date IS NULL AND end_date IS NULL) OR (start_date IS NOT NULL AND end_date IS NOT NULL AND start_date <= end_date))
);

CREATE INDEX IF NOT EXISTS ix_txn_supplemental_line_txn ON txn_supplemental_line(txn_id);
CREATE INDEX IF NOT EXISTS ix_txn_supplemental_line_kind ON txn_supplemental_line(kind);
