-- P15-S6-C3: durable, company-owned bank CSV mapping profiles.
CREATE TABLE bank_csv_mapping_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portable_id UUID NOT NULL DEFAULT RANDOM_UUID(),
    company_id BIGINT NOT NULL,
    bank_account_id BIGINT NOT NULL,
    profile_name VARCHAR(160) NOT NULL,
    profile_version VARCHAR(20) NOT NULL,
    delimiter VARCHAR(10) NOT NULL,
    source_encoding VARCHAR(20) NOT NULL,
    amount_mode VARCHAR(30) NOT NULL,
    fixed_currency VARCHAR(3),
    fixed_account_id VARCHAR(160),
    mapping_json CLOB NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bank_csv_profile_company FOREIGN KEY (company_id) REFERENCES company(id),
    CONSTRAINT fk_bank_csv_profile_bank_account FOREIGN KEY (bank_account_id) REFERENCES company_bank_account(id),
    CONSTRAINT uq_bank_csv_profile_portable UNIQUE (portable_id),
    CONSTRAINT uq_bank_csv_profile_name_version UNIQUE (company_id, bank_account_id, profile_name, profile_version),
    CONSTRAINT ck_bank_csv_profile_delimiter CHECK (delimiter IN (',', 'TAB', ';', '|')),
    CONSTRAINT ck_bank_csv_profile_encoding CHECK (source_encoding IN ('UTF-8', 'US-ASCII', 'WINDOWS-1252')),
    CONSTRAINT ck_bank_csv_profile_amount_mode CHECK (amount_mode IN ('SIGNED_AMOUNT', 'DEBIT_CREDIT'))
);

CREATE INDEX ix_bank_csv_profile_company_account_active
    ON bank_csv_mapping_profile(company_id, bank_account_id, is_active);
