CREATE TABLE IF NOT EXISTS fixed_asset_lifecycle_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portable_id UUID NOT NULL DEFAULT RANDOM_UUID(),
    fixed_asset_id BIGINT NOT NULL,
    event_type VARCHAR(24) NOT NULL,
    event_date DATE NOT NULL,
    acquisition_cost DECIMAL(19,4) NOT NULL,
    accumulated_depreciation DECIMAL(19,4) NOT NULL,
    accumulated_impairment_before DECIMAL(19,4) NOT NULL,
    carrying_amount_before DECIMAL(19,4) NOT NULL,
    proceeds DECIMAL(19,4) NOT NULL DEFAULT 0,
    impairment_amount DECIMAL(19,4) NOT NULL DEFAULT 0,
    gain_amount DECIMAL(19,4) NOT NULL DEFAULT 0,
    loss_amount DECIMAL(19,4) NOT NULL DEFAULT 0,
    proceeds_account_id BIGINT,
    gain_account_id BIGINT,
    loss_account_id BIGINT,
    transaction_id BIGINT NOT NULL,
    reversal_transaction_id BIGINT,
    asset_status_before VARCHAR(40) NOT NULL,
    asset_status_after VARCHAR(40) NOT NULL,
    notes CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reversed_at TIMESTAMP,
    CONSTRAINT uq_fixed_asset_lifecycle_portable_id UNIQUE (portable_id),
    CONSTRAINT uq_fixed_asset_lifecycle_transaction UNIQUE (transaction_id),
    CONSTRAINT uq_fixed_asset_lifecycle_reversal UNIQUE (reversal_transaction_id),
    CONSTRAINT fk_fixed_asset_lifecycle_asset FOREIGN KEY (fixed_asset_id) REFERENCES fixed_asset(id),
    CONSTRAINT fk_fixed_asset_lifecycle_proceeds_account FOREIGN KEY (proceeds_account_id) REFERENCES account(id),
    CONSTRAINT fk_fixed_asset_lifecycle_gain_account FOREIGN KEY (gain_account_id) REFERENCES account(id),
    CONSTRAINT fk_fixed_asset_lifecycle_loss_account FOREIGN KEY (loss_account_id) REFERENCES account(id),
    CONSTRAINT fk_fixed_asset_lifecycle_transaction FOREIGN KEY (transaction_id) REFERENCES txn(id),
    CONSTRAINT fk_fixed_asset_lifecycle_reversal FOREIGN KEY (reversal_transaction_id) REFERENCES txn(id),
    CONSTRAINT ck_fixed_asset_lifecycle_type CHECK (event_type IN ('SALE', 'RETIREMENT', 'IMPAIRMENT')),
    CONSTRAINT ck_fixed_asset_lifecycle_status_before CHECK (asset_status_before IN ('ACTIVE', 'INACTIVE', 'DISPOSED')),
    CONSTRAINT ck_fixed_asset_lifecycle_status_after CHECK (asset_status_after IN ('ACTIVE', 'INACTIVE', 'DISPOSED')),
    CONSTRAINT ck_fixed_asset_lifecycle_amounts CHECK (
        acquisition_cost >= 0 AND accumulated_depreciation >= 0
        AND accumulated_impairment_before >= 0 AND carrying_amount_before >= 0
        AND proceeds >= 0 AND impairment_amount >= 0 AND gain_amount >= 0 AND loss_amount >= 0),
    CONSTRAINT ck_fixed_asset_lifecycle_reversal_pair CHECK (
        (reversal_transaction_id IS NULL AND reversed_at IS NULL)
        OR (reversal_transaction_id IS NOT NULL AND reversed_at IS NOT NULL)),
    CONSTRAINT ck_fixed_asset_lifecycle_distinct_txns CHECK (
        reversal_transaction_id IS NULL OR reversal_transaction_id <> transaction_id)
);

CREATE INDEX IF NOT EXISTS ix_fixed_asset_lifecycle_asset
    ON fixed_asset_lifecycle_event(fixed_asset_id, event_date);
CREATE INDEX IF NOT EXISTS ix_fixed_asset_lifecycle_txn
    ON fixed_asset_lifecycle_event(transaction_id);
CREATE INDEX IF NOT EXISTS ix_fixed_asset_lifecycle_reversal
    ON fixed_asset_lifecycle_event(reversal_transaction_id);
