ALTER TABLE app_user ADD COLUMN IF NOT EXISTS reserved_security_code VARCHAR(20);
ALTER TABLE app_role ADD COLUMN IF NOT EXISTS reserved_security_code VARCHAR(20);

ALTER TABLE app_user ADD CONSTRAINT IF NOT EXISTS ck_app_user_reserved_security_code
    CHECK (reserved_security_code IS NULL OR reserved_security_code IN ('ADMIN', 'MANAGER', 'ACCOUNTANT', 'VIEWER'));
ALTER TABLE app_role ADD CONSTRAINT IF NOT EXISTS ck_app_role_reserved_security_code
    CHECK (reserved_security_code IS NULL OR reserved_security_code IN ('ADMIN', 'MANAGER', 'ACCOUNTANT', 'VIEWER'));

CREATE UNIQUE INDEX IF NOT EXISTS uq_app_user_reserved_security_code
    ON app_user (reserved_security_code);
CREATE UNIQUE INDEX IF NOT EXISTS uq_app_role_reserved_security_code
    ON app_role (reserved_security_code);

-- V46 created these four role definitions as application-owned bootstrap data.
UPDATE app_role SET reserved_security_code = 'ADMIN'
WHERE UPPER(code) = 'ADMIN' AND reserved_security_code IS NULL;
UPDATE app_role SET reserved_security_code = 'MANAGER'
WHERE UPPER(code) = 'MANAGER' AND reserved_security_code IS NULL;
UPDATE app_role SET reserved_security_code = 'ACCOUNTANT'
WHERE UPPER(code) = 'ACCOUNTANT' AND reserved_security_code IS NULL;
UPDATE app_role SET reserved_security_code = 'VIEWER'
WHERE UPPER(code) = 'VIEWER' AND reserved_security_code IS NULL;

CREATE TABLE IF NOT EXISTS app_user_credential (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    algorithm VARCHAR(64) NOT NULL,
    iteration_count INT NOT NULL,
    salt_base64 VARCHAR(128) NOT NULL,
    hash_base64 VARCHAR(256) NOT NULL,
    credential_version INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_app_user_credential_user UNIQUE (user_id),
    CONSTRAINT fk_app_user_credential_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT ck_app_user_credential_iterations CHECK (iteration_count > 0),
    CONSTRAINT ck_app_user_credential_version CHECK (credential_version > 0)
);

CREATE INDEX IF NOT EXISTS ix_app_user_credential_user ON app_user_credential (user_id);

CREATE TABLE IF NOT EXISTS security_configuration (
    id BIGINT PRIMARY KEY,
    bootstrap_initialized BOOLEAN NOT NULL DEFAULT FALSE,
    inactivity_timeout_minutes INT NOT NULL DEFAULT 0,
    admin_recovery_pending BOOLEAN NOT NULL DEFAULT FALSE,
    admin_recovery_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_security_configuration_singleton CHECK (id = 1),
    CONSTRAINT ck_security_configuration_timeout CHECK (inactivity_timeout_minutes >= 0)
);

MERGE INTO security_configuration
    (id, bootstrap_initialized, inactivity_timeout_minutes, admin_recovery_pending, created_at, updated_at)
KEY (id)
VALUES
    (1, FALSE, 0, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS security_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    company_id BIGINT,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    action_type VARCHAR(80) NOT NULL,
    subject_username VARCHAR(80),
    summary VARCHAR(500) NOT NULL,
    details VARCHAR(2000),
    CONSTRAINT fk_security_event_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_security_event_company FOREIGN KEY (company_id) REFERENCES company (id)
);

CREATE INDEX IF NOT EXISTS ix_security_event_time ON security_event (occurred_at);
CREATE INDEX IF NOT EXISTS ix_security_event_user_time ON security_event (user_id, occurred_at);
CREATE INDEX IF NOT EXISTS ix_security_event_company_time ON security_event (company_id, occurred_at);
CREATE INDEX IF NOT EXISTS ix_security_event_action_time ON security_event (action_type, occurred_at);
